### ISSUE TITLE
Book of Beliefs: Links to old yearly reports are broken

### ISSUE THREAD

**Issue by arjunblj** [busterbenson/public#10]
Hey Buster,

Links to http://enjoymentland.com/ via the "Yearly reports" here: https://github.com/busterbenson/public/blob/master/Codex2015.md#yearly-reports are broken (years 33 and 34).

Thanks for putting the work into making all this public!

**Comment by busterbenson** [comment]
Oops, looks like I let that domain expire. Will need to find another way to link to those entries. Thanks for the catch.

**Comment by busterbenson** [comment]
After completely giving up on finding these articles again, I realized that I have the text stored in my own database. I will try to re-build them to look nice again, but they're here: 

34: http://busterbenson.com/week_of/2010-05-28
33: http://busterbenson.com/week_of/2009-05-28

**Comment by busterbenson** [comment]
Finally fixed these.

**Comment by arjunblj** [comment]
Awesome!
