### ISSUE TITLE
WayOfTheDuck.com broken links

### ISSUE THREAD

**Issue by frangdlt** [busterbenson/public#16]
The following files have links pointing to WayOfTheDuck.com , which is now under somebody else's control.

- book-of-beliefs.md
- book-of-beliefs-2014.md
- book-of-beliefs-2015.md
- book-of-beliefs-2016.md

The files should be updated pointing to the right URL if possible.

**Comment by busterbenson** [comment]
Fixed these in the latest PR. Thank you for pointing them out!
