### ISSUE TITLE
Acupuncture and the Endocannabinoid System

### ISSUE THREAD

**Issue by supaspoida** [busterbenson/public#5]
I was reading through your codex & thought you might be interested to know that there is some evidence that acupuncture works by interacting with cannabinoid receptors that have anti-inflammatory properties. These receptors are part of a larger endocannabinoid system that we're only now starting to discover. So your point #8 on Morality has the potential to bridge the gap between eastern medicine and western science, as legalization allows research to begin to catch up with technology.

Here is a study with all the sciency details: http://www.ncbi.nlm.nih.gov/pubmed/23762129

I realize filing an issue is an odd way to pass this along, but a pull request didn't feel right either.

**Comment by busterbenson** [comment]
Thanks for the info!
