### ISSUE TITLE
"Tappable" essay is gone

### ISSUE THREAD

**Issue by DivineDominion** [busterbenson/public#6]
The link of "If You Live 100 Times: A tappable essay that plays out 100 lives that you could live." is broken. It leads to their landing page instead.

**Comment by jonathan-s** [comment]
Here is a link @DivineDominion http://cdn.readtapestry.com/stories/RVwPvalHq/index.html

**Comment by busterbenson** [comment]
Thank you! Fixed with https://github.com/busterbenson/public/commit/0e34d70c0e007e9c6cdf8313a52e44b4acf399e8

**Comment by drecali** [comment]
The link doesn't work. Is it available elsewhere? Sounds fascinating!

**Comment by DivineDominion** [comment]
Web archive to the rescue, this is the only thing I could find:
http://web.archive.org/web/20131207084606/https://readtapestry.com/s/RVwPvalHq/
